### ISSUE TITLE
A variable is called as a constant

### ISSUE THREAD

**Issue by vannicaruso** [uwejacobs/owm-weather#1]
Hi,
at line 3477 there is a call to the $owmw_opt variable without the dollar sign.

The error is:

[03-Sep-2023 13:49:42 UTC] PHP Fatal error:  Uncaught Error: Undefined constant "owmw_opt" in /home/wp-content/plugins/owm-weather/owmweather.php:3478
Stack trace:
#0 /home/wp-includes/class-wp-hook.php(310): owmw_get_my_weather()
#1 /home/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#2 /home/wp-includes/plugin.php(517): WP_Hook->do_action()
#3 /home/wp-admin/admin-ajax.php(188): do_action()
#4 {main}
  thrown in /home/wp-content/plugins/owm-weather/owmweather.php on line 3478

**Comment by uwejacobs** [comment]
Thanks for letting me know! Not sure how this one slipped through.

In any case, I fixed the issue with version 5.7.1.
